### ISSUE TITLE
Rakdos doesn't respond anymore

### ISSUE THREAD

**Issue by steevefontaine** [filipekiss/rakdos#155]
Rakdos doesn't respondy anymore. It doesn't work in inline mode nor in trigger mode. It doesn't work with any card name.

I tested on Telegram Desktop 2.3.1 on Ubuntu 20.04 and Telegram 7.0.0 on Android 8.1.0.

It seems that the latest Scryfall API update is the source of the problem. See more here: https://scryfall.com/blog/upcoming-api-changes-to-scryfall-image-uris-and-download-uris-221

**Comment by filipekiss** [comment]
Hey @MHostile, thanks for reaching out and sorry for the delay. Rakdos should be up and running again!
